name: ui
description: Shared UI Components, Widgets, Fonts, Colors and Theme
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: ">=3.27.1"

# https://dart.dev/tools/pub/workspaces
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  intl:
  collection:
  #google_fonts:

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true